name: database-clusters

services:
  mongodb:
    container_name: mongodb
    restart: unless-stopped
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  elasticsearch:
    container_name: elasticsearch
    restart: unless-stopped
    image: elasticsearch:9.1.5
    ports:
      - 19200:9200
      - 19300:9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - ELASTIC_PASSWORD=admin
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx4g"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
  kibana:
    container_name: kibana
    restart: unless-stopped
    image: kibana:9.1.5
    ports:
      - "15601:5601"
    depends_on:
      - elasticsearch

volumes:
  mongodb_data:
    external: true
  elasticsearch_data:
    external: true
