servers:
  devbox: localhost
#  devbox: 10.0.0.143
#  devbox: 192.168.68.103

spring:
  data:
    mongodb:
      database: organization-service
      host: mongo
      port: 27017
      auto-index-creation: true
#      username: admin
#      password: 2z1^tez8

services:
  elastic-search:
    base-url: http://elasticsearch:19200